# export_sim.tcl
#
# Vivado TCL script that exports all simulation files (IP models, BD wrapper,
# compile scripts) for Questasim from an existing Vivado project.
#
# This only needs to be re-run when IP cores, the Block Design, or the HDL
# source files change — not on every ELF rebuild.
#
# The exported directory contains:
#   - A compile script  (<top>_compile.do) with all vlog/vcom commands
#   - A run script      (<top>_simulate.do) generated by Vivado (optional)
#   - IP simulation model sources
#
# The sim.do in this library sources <top>_compile.do rather than using the
# Vivado-generated run script, giving full control over vsim arguments and
# the mem load step.
#
# Usage (batch mode):
#   vivado -mode batch -source export_sim.tcl \
#     -tclargs <PROJECT_XPR> <OUTPUT_DIR>
#
# Arguments (positional, via -tclargs):
#   PROJECT_XPR  - Path to the .xpr Vivado project file
#   OUTPUT_DIR   - Root output directory; sim files go into OUTPUT_DIR/questa_sim/

# ---------------------------------------------------------------------------
# Parse arguments
# ---------------------------------------------------------------------------
if { $argc != 2 } {
    puts "Usage: vivado -mode batch -source export_sim.tcl \\"
    puts "         -tclargs <PROJECT_XPR> <OUTPUT_DIR>"
    exit 1
}

set project_xpr [file normalize [lindex $argv 0]]
set output_dir  [file normalize [lindex $argv 1]]
set questa_dir  [file join $output_dir questa_sim]

puts "INFO: export_sim.tcl"
puts "INFO:   PROJECT_XPR = $project_xpr"
puts "INFO:   OUTPUT_DIR  = $output_dir"
puts "INFO:   QUESTA_DIR  = $questa_dir"

# ---------------------------------------------------------------------------
# Input validation
# ---------------------------------------------------------------------------
if { ![file exists $project_xpr] } {
    puts "ERROR: Project file not found: $project_xpr"
    exit 1
}

file mkdir $questa_dir

# ---------------------------------------------------------------------------
# Open project
# ---------------------------------------------------------------------------
puts "INFO: Opening project: $project_xpr"
if { [catch { open_project $project_xpr } err] } {
    puts "ERROR: Failed to open project: $err"
    exit 1
}

# ---------------------------------------------------------------------------
# Export simulation files for Questasim
#
# Flags used:
#   -simulator questa         : Target simulator
#   -ip_user_files_dir        : Where Vivado writes IP user files (sources)
#   -ipstatic_source_dir      : Shared IP static sources (reduces duplication)
#   -lib_map_path             : Path to pre-compiled Vivado sim libs for Questasim.
#                               Optional here; can also be specified in sim.do via
#                               vsim -L flags. Leave empty to skip library mapping.
#   -use_ip_compiled_libs     : Reference already-compiled IP libs rather than
#                               re-compiling them every time (faster).
#   -force                    : Overwrite existing output
#   -directory                : Root output directory
#   -include_all_compile_units: Export all compile units, not just the top-level.
#                               Required when the BD contains sub-BDs or IPs that
#                               have their own simulation models.
# ---------------------------------------------------------------------------
puts "INFO: Exporting simulation files..."

set export_args {
    -simulator questa
    -force
    -include_all_compile_units
    -directory
}
lappend export_args $questa_dir

if { [catch { export_simulation {*}$export_args } err] } {
    puts "ERROR: export_simulation failed: $err"
    close_project
    exit 1
}

puts "INFO: export_simulation completed."
puts "INFO: Questa simulation files written to: $questa_dir"

# ---------------------------------------------------------------------------
# Locate the generated compile script so the user knows what to source
# ---------------------------------------------------------------------------
set compile_scripts [glob -nocomplain [file join $questa_dir "*_compile.do"]]
if { [llength $compile_scripts] > 0 } {
    puts ""
    puts "INFO: Generated compile script(s):"
    foreach s $compile_scripts {
        puts "INFO:   [file tail $s]"
    }
    puts ""
    puts "INFO: In sim.do, this script is sourced automatically via the"
    puts "INFO: QUESTA_COMPILE_DO variable."
} else {
    puts "WARNING: No *_compile.do file found in $questa_dir"
    puts "         Check that the project has a sim_1 simulation fileset."
}

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
close_project

puts ""
puts "INFO: export_sim.tcl completed successfully."
