# export_sim.tcl
#
# Vivado TCL script that exports all simulation files (IP models, BD wrapper,
# compile scripts) for Questasim from an existing Vivado project.
#
# This only needs to be re-run when IP cores, the Block Design, or the HDL
# source files change — not on every ELF rebuild.
#
# The exported directory contains:
#   - A compile script  (<top>_compile.do) with all vlog/vcom commands
#   - A run script      (<top>_simulate.do) generated by Vivado (optional)
#   - IP simulation model sources
#
# The sim.do in this library sources <top>_compile.do rather than using the
# Vivado-generated run script, giving full control over vsim arguments and
# the mem load step.
#
# Usage (batch mode):
#   vivado -mode batch -source export_sim.tcl \
#     -tclargs <PROJECT_XPR> <OUTPUT_DIR>
#
# Arguments (positional, via -tclargs):
#   PROJECT_XPR  - Path to the .xpr Vivado project file
#   OUTPUT_DIR   - Root output directory; sim files go into OUTPUT_DIR/questa_sim/

source [file join [file dirname [info script]] ../tcl/utils.tcl]

timer_start "total"

log_section "export_sim — Vivado → Questasim file export"

# ---------------------------------------------------------------------------
# Parse arguments
# ---------------------------------------------------------------------------
if { $argc != 2 } {
    puts "Usage: vivado -mode batch -source export_sim.tcl \\"
    puts "         -tclargs <PROJECT_XPR> <OUTPUT_DIR>"
    exit 1
}

set project_xpr [file normalize [lindex $argv 0]]
set output_dir  [file normalize [lindex $argv 1]]
set questa_dir  [file join $output_dir questa_sim]

log_info "Configuration:"
log_kv "PROJECT_XPR" $project_xpr
log_kv "OUTPUT_DIR"  $output_dir
log_kv "QUESTA_DIR"  $questa_dir
hr

# ---------------------------------------------------------------------------
# Input validation
# ---------------------------------------------------------------------------
require_file $project_xpr "Vivado project (.xpr)"
require_dir  $questa_dir  "Questasim output directory" 1

# ---------------------------------------------------------------------------
# Step 1: Open project
# ---------------------------------------------------------------------------
log_step 1 "Open Vivado project"
timer_start "open_project"

if { [catch { open_project $project_xpr } err] } {
    die "Failed to open project: $err"
}

log_ok "Project opened"
timer_stop "open_project" "open_project"

# ---------------------------------------------------------------------------
# Step 2: Export simulation files for Questasim
#
# Flags used:
#   -simulator questa         : Target simulator
#   -force                    : Overwrite any existing export
#   -include_all_compile_units: Export every compile unit (required when the BD
#                               contains sub-BDs or IPs with their own sim models)
#   -directory                : Root output path
#
# Optional flags (commented out — enable if needed):
#   -ip_user_files_dir  <dir> : Override where Vivado writes IP user files
#   -ipstatic_source_dir <dir>: Shared IP static sources (reduces duplication)
#   -lib_map_path <ini>       : Pre-compiled Questasim library map.  It is
#                               usually easier to supply SIM_LIB_DIR via sim.do
#                               so that export_sim.tcl stays machine-independent.
#   -use_ip_compiled_libs     : Reference pre-compiled IP libs (faster) — only
#                               valid when -lib_map_path is also supplied.
# ---------------------------------------------------------------------------
log_step 2 "Export simulation files (export_simulation)"
timer_start "export_sim"

set export_args [list \
    -simulator            questa \
    -force                        \
    -include_all_compile_units    \
    -directory            $questa_dir \
]

log_cmd export_simulation {*}$export_args

if { [catch { export_simulation {*}$export_args } err] } {
    die "export_simulation failed: $err" \
        "Check that the project has a 'sim_1' simulation fileset."
}

log_ok "export_simulation completed"
timer_stop "export_sim" "export_simulation"

# ---------------------------------------------------------------------------
# Report generated compile scripts
# ---------------------------------------------------------------------------
set compile_scripts [glob -nocomplain [file join $questa_dir "*_compile.do"]]
if { [llength $compile_scripts] > 0 } {
    log_info "Generated compile script(s):"
    foreach s $compile_scripts {
        log_kv "  compile script" [file tail $s]
    }
    log_info "QUESTA_COMPILE_DO in the Makefile points to this file automatically."
} else {
    log_warn "No *_compile.do found in $questa_dir"
    log_warn "Check that the project has a sim_1 simulation fileset."
}

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
close_project

hr "═"
log_ok "export_sim completed  ([timer_elapsed_str total])"
hr "═"
puts ""
log_info "Output directory: $questa_dir"
log_info "Run 'make gen-mem' next to convert your ELF to BRAM init files."
