# sim.do
#
# Questasim 2022.4 master do-file for simulating an AMD/Xilinx Block Design
# containing a MicroBlaze core, with firmware loaded from an ELF file.
#
# Flow:
#   1. Create / refresh the work library
#   2. Source the Vivado-exported compile script to build all IP models
#   3. Elaborate (vsim) the testbench top
#   4. Source load_elf.tcl (generated by write_mem_tcl) to load firmware into
#      BRAM via Questasim "mem load" commands
#   5. Optionally load waveforms
#   6. Run the simulation
#
# This script is driven by environment variables set by the Makefile.
# All variables have defaults so the file can also be used standalone.
#
# Environment variables:
#   QUESTA_WORK_LIB     - Work library name                   (default: work)
#   QUESTA_COMPILE_DO   - Path to Vivado-exported *_compile.do
#   QUESTA_SIM_TOP      - Testbench top module name
#   QUESTA_SIM_LIB_DIR  - Path to pre-compiled Vivado Questasim libraries
#   QUESTA_LOAD_ELF_TCL - Path to load_elf.tcl from write_mem_tcl
#   QUESTA_WAVE_DO      - Path to wave.do  (empty string = skip waveforms)
#   QUESTA_RUN_TIME     - Argument to "run"                   (default: -all)
#   VSIM_EXTRA_ARGS     - Extra flags forwarded to vsim
#   QUESTA_BATCH        - "1" = quit after simulation (CI / batch mode)
#   TB_INST_PREFIX      - Prepended to BRAM hierarchy paths in load_elf.tcl
#                         when your testbench wraps the DUT under a non-default
#                         path (e.g. "/tb_top/DUT")

source [file join [file dirname [info script]] ../tcl/utils.tcl]

timer_start "total"

log_section "sim.do — Questasim MicroBlaze ELF simulation"

# ---------------------------------------------------------------------------
# Configuration (environment variables with defaults)
# ---------------------------------------------------------------------------
set work_lib     [getenv QUESTA_WORK_LIB     "work"]
set compile_do   [getenv QUESTA_COMPILE_DO   ""]
set sim_top      [getenv QUESTA_SIM_TOP      "tb_top"]
set sim_lib_dir  [getenv QUESTA_SIM_LIB_DIR  ""]
set load_elf_tcl [getenv QUESTA_LOAD_ELF_TCL ""]
set wave_do      [getenv QUESTA_WAVE_DO      [file join [file dirname [info script]] wave.do]]
set run_time     [getenv QUESTA_RUN_TIME     "-all"]
set vsim_extra   [getenv VSIM_EXTRA_ARGS     ""]
set batch_mode   [getenv QUESTA_BATCH        "0"]
set tb_prefix    [getenv TB_INST_PREFIX      ""]

log_info "Configuration:"
log_kv "work_lib"     $work_lib
log_kv "compile_do"   $compile_do
log_kv "sim_top"      $sim_top
log_kv "sim_lib_dir"  [expr { $sim_lib_dir eq "" ? "(not set)" : $sim_lib_dir }]
log_kv "load_elf_tcl" $load_elf_tcl
log_kv "wave_do"      [expr { $wave_do eq "" ? "(disabled)" : $wave_do }]
log_kv "run_time"     $run_time
log_kv "batch_mode"   $batch_mode
log_kv "tb_prefix"    [expr { $tb_prefix eq "" ? "(none)" : $tb_prefix }]
hr

# ---------------------------------------------------------------------------
# Validate required inputs
# ---------------------------------------------------------------------------
require_file $compile_do   "Compile script (QUESTA_COMPILE_DO)" \
    "Run 'make export-sim' to generate it."
require_file $load_elf_tcl "ELF load script (QUESTA_LOAD_ELF_TCL)" \
    "Run 'make gen-mem' to generate it."

# ---------------------------------------------------------------------------
# Step 1: Create / refresh the work library
# ---------------------------------------------------------------------------
log_step 1 "Create work library"
timer_start "vlib"

if { [file exists $work_lib] } {
    log_info "Removing stale library: $work_lib"
    vdel -lib $work_lib -all
}
vlib $work_lib
vmap work $work_lib

log_ok "Work library ready: $work_lib"
timer_stop "vlib" "vlib"

# ---------------------------------------------------------------------------
# Step 2: Map pre-compiled Vivado simulation libraries
#
# The compile script generated by export_simulation references libraries such
# as xil_defaultlib, xpm, blk_mem_gen_v8_4_5, etc.  Pre-compiled versions of
# these are produced once via Vivado: Tools → Compile Simulation Libraries.
#
# Vivado writes a modelsim.ini into SIM_LIB_DIR that maps each library name
# to its on-disk path.  We parse it here and issue vmap for each entry.
# ---------------------------------------------------------------------------
log_step 2 "Map pre-compiled simulation libraries"
timer_start "vmap"

if { $sim_lib_dir eq "" } {
    log_warn "QUESTA_SIM_LIB_DIR is not set — skipping library mapping."
    log_warn "Elaboration may fail with 'library not found' if IP models reference"
    log_warn "Vivado pre-compiled libraries (xil_defaultlib, xpm, etc.)."
} elseif { ![file isdirectory $sim_lib_dir] } {
    log_warn "SIM_LIB_DIR does not exist: $sim_lib_dir"
    log_warn "Proceeding without pre-compiled library mapping."
} else {
    set ini_file [file join $sim_lib_dir "modelsim.ini"]
    if { ![file exists $ini_file] } {
        log_warn "modelsim.ini not found in $sim_lib_dir"
        log_warn "Set SIM_LIB_DIR to the directory produced by 'Compile Simulation Libraries'."
    } else {
        vmap -c   ;# create/reset local mapping before adding entries
        set fd [open $ini_file r]
        set mapped 0
        while { [gets $fd line] >= 0 } {
            # modelsim.ini lines: LibraryName = /path/to/compiled/lib
            if { [regexp {^(\w[\w.]*)\s*=\s*(.+)$} $line -> libname libpath] } {
                if { [catch { vmap $libname [string trim $libpath] }] == 0 } {
                    incr mapped
                }
            }
        }
        close $fd
        log_ok "Mapped $mapped simulation libraries from [file tail $ini_file]"
    }
}

timer_stop "vmap" "library mapping"

# ---------------------------------------------------------------------------
# Step 3: Compile the design
#
# Source the Vivado-generated compile script.  It contains all vlog / vcom
# commands needed to build IP models, the Block Design HDL wrapper, and any
# user HDL in the simulation fileset.
# ---------------------------------------------------------------------------
log_step 3 "Compile design (sourcing [file tail $compile_do])"
timer_start "compile"

log_cmd do $compile_do
do $compile_do

log_ok "Compilation complete"
timer_stop "compile" "compilation"

# ---------------------------------------------------------------------------
# Step 4: Elaborate (vsim)
#
# Key flags:
#   -t 1ps          : Simulation time resolution
#   +acc            : Full signal / memory access — REQUIRED for mem load
#   -onfinish stop  : Pause at $finish rather than exiting so state is inspectable
#
# The "+acc" flag is critical: without it Questasim restricts write access to
# internal memory arrays and the "mem load" commands will silently fail.
# ---------------------------------------------------------------------------
log_step 4 "Elaborate testbench (vsim $sim_top)"
timer_start "vsim"

set vsim_flags [list -t 1ps +acc -onfinish stop]

# Append pre-compiled library references when a lib dir was provided
if { $sim_lib_dir ne "" && [file isdirectory $sim_lib_dir] } {
    lappend vsim_flags -L xil_defaultlib -L xpm -L blk_mem_gen_v8_4_5
    # Add further -L flags here for other IP libraries used in your design
}

if { $vsim_extra ne "" } {
    lappend vsim_flags {*}[split $vsim_extra]
}

log_cmd vsim {*}$vsim_flags $sim_top
vsim {*}$vsim_flags $sim_top

log_ok "Elaboration complete"
timer_stop "vsim" "vsim elaboration"

# ---------------------------------------------------------------------------
# Step 5: Load ELF firmware into BRAM via mem load
#
# load_elf.tcl was produced by Vivado's write_mem_tcl.  It contains commands:
#
#   mem load -infile /path/to/bram_init_0.mem -format hex \
#            /tb/DUT/bd_i/blk_mem_gen_0/U0/...
#
# If TB_INST_PREFIX is set, the hierarchy paths are rewritten on the fly to
# prepend the prefix, accommodating testbenches where the DUT lives under a
# non-standard path.
# ---------------------------------------------------------------------------
log_step 5 "Load ELF into BRAM (mem load)"
timer_start "mem_load"

if { $tb_prefix ne "" } {
    log_info "Applying TB_INST_PREFIX \"$tb_prefix\" to mem load hierarchy paths..."
    set patched_tcl "${load_elf_tcl}.patched"
    set fd_in  [open $load_elf_tcl r]
    set fd_out [open $patched_tcl   w]
    while { [gets $fd_in line] >= 0 } {
        # Rewrite the final path argument on every "mem load" line
        regsub {(mem\s+load\s+(?:-\S+\s+\S+\s+)*)(\/\S+)\s*$} \
               $line "\\1${tb_prefix}\\2" line
        puts $fd_out $line
    }
    close $fd_in
    close $fd_out
    set active_load_tcl $patched_tcl
} else {
    set active_load_tcl $load_elf_tcl
}

log_cmd source $active_load_tcl
source $active_load_tcl

# Count successful mem load calls as a quick sanity check
set fd [open $active_load_tcl r]
set load_count [llength [regexp -all -inline {^\s*mem\s+load} [read $fd]]]
close $fd
log_ok "ELF loaded ($load_count BRAM region(s))"
timer_stop "mem_load" "mem load"

# ---------------------------------------------------------------------------
# Step 6: Waveforms (interactive mode only)
# ---------------------------------------------------------------------------
if { $batch_mode ne "1" && $wave_do ne "" && [file exists $wave_do] } {
    log_step 6 "Configure waveforms"
    log_cmd do $wave_do
    do $wave_do
}

# ---------------------------------------------------------------------------
# Step 7: Run
# ---------------------------------------------------------------------------
log_step 7 "Run simulation"
timer_start "run"

log_cmd run $run_time
run $run_time

timer_stop "run" "simulation run"

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
hr "═"
log_ok "Simulation complete  ([timer_elapsed_str total])"
hr "═"

if { $batch_mode eq "1" } {
    quit -f
}
