# sim.do
#
# Questasim 2022.4 master do-file for simulating an AMD/Xilinx Block Design
# containing a MicroBlaze core, with firmware loaded from an ELF file.
#
# Flow:
#   1. Create / refresh the work library
#   2. Source the Vivado-exported compile script to build all IP models
#   3. Elaborate (vsim) the testbench top
#   4. Source the load_elf.tcl generated by Vivado's write_mem_tcl to load
#      firmware into BRAM via "mem load" commands
#   5. Optionally load waveforms
#   6. Run the simulation
#
# This script is driven by environment variables set by the Makefile.
# All variables have defaults so the file can also be used standalone.
#
# Environment variables:
#   QUESTA_WORK_LIB     - Work library name           (default: work)
#   QUESTA_COMPILE_DO   - Path to Vivado-exported *_compile.do script
#   QUESTA_SIM_TOP      - Testbench top module name
#   QUESTA_SIM_LIB_DIR  - Path to pre-compiled Vivado Questasim libraries
#   QUESTA_LOAD_ELF_TCL - Path to load_elf.tcl from write_mem_tcl
#   QUESTA_WAVE_DO      - Path to wave.do  (set to "" to skip waveforms)
#   QUESTA_RUN_TIME     - Argument to "run" command    (default: -all)
#   VSIM_EXTRA_ARGS     - Extra flags forwarded to vsim
#   QUESTA_BATCH        - Set to "1" to quit after simulation (CI/batch use)

# ---------------------------------------------------------------------------
# Helper: read an environment variable with a fallback default
# ---------------------------------------------------------------------------
proc getenv { name default } {
    if { [info exists ::env($name)] && $::env($name) ne "" } {
        return $::env($name)
    }
    return $default
}

# ---------------------------------------------------------------------------
# Configuration (from environment or defaults)
# ---------------------------------------------------------------------------
set work_lib      [getenv QUESTA_WORK_LIB      "work"]
set compile_do    [getenv QUESTA_COMPILE_DO     ""]
set sim_top       [getenv QUESTA_SIM_TOP        "tb_top"]
set sim_lib_dir   [getenv QUESTA_SIM_LIB_DIR    ""]
set load_elf_tcl  [getenv QUESTA_LOAD_ELF_TCL   ""]
set wave_do       [getenv QUESTA_WAVE_DO        "[file join [file dirname [info script]] wave.do]"]
set run_time      [getenv QUESTA_RUN_TIME       "-all"]
set vsim_extra    [getenv VSIM_EXTRA_ARGS       ""]
set batch_mode    [getenv QUESTA_BATCH          "0"]

puts "INFO: sim.do configuration:"
puts "INFO:   work_lib     = $work_lib"
puts "INFO:   compile_do   = $compile_do"
puts "INFO:   sim_top      = $sim_top"
puts "INFO:   sim_lib_dir  = $sim_lib_dir"
puts "INFO:   load_elf_tcl = $load_elf_tcl"
puts "INFO:   wave_do      = $wave_do"
puts "INFO:   run_time     = $run_time"
puts "INFO:   batch_mode   = $batch_mode"

# ---------------------------------------------------------------------------
# Validate required inputs
# ---------------------------------------------------------------------------
if { $compile_do eq "" } {
    error "QUESTA_COMPILE_DO is not set. Export simulation files from Vivado first (make export-sim)."
}
if { ![file exists $compile_do] } {
    error "Compile script not found: $compile_do\nRun 'make export-sim' to generate it."
}
if { $load_elf_tcl eq "" } {
    error "QUESTA_LOAD_ELF_TCL is not set. Generate mem files first (make gen-mem)."
}
if { ![file exists $load_elf_tcl] } {
    error "ELF load script not found: $load_elf_tcl\nRun 'make gen-mem' to generate it."
}

# ---------------------------------------------------------------------------
# Step 1: Create / refresh the work library
# ---------------------------------------------------------------------------
if { [file exists $work_lib] } {
    vdel -lib $work_lib -all
}
vlib $work_lib
vmap work $work_lib

# ---------------------------------------------------------------------------
# Step 2: Map pre-compiled Vivado simulation libraries (if provided)
#
# The compile script generated by export_simulation references libraries such
# as xil_defaultlib, xpm, blk_mem_gen_v8_4_5, etc.  These must be mapped
# before sourcing the compile script.
#
# The modelsim.ini / library mapping file produced by Vivado's
# "Compile Simulation Libraries" wizard is located inside SIM_LIB_DIR.
# We add it as an extra mapping path so Questasim finds the prebuilt libs.
# ---------------------------------------------------------------------------
if { $sim_lib_dir ne "" } {
    if { ![file exists $sim_lib_dir] } {
        puts "WARNING: SIM_LIB_DIR does not exist: $sim_lib_dir"
        puts "         Proceeding without pre-compiled library mapping."
        puts "         This may cause 'library not found' errors during elaboration."
    } else {
        # Map every library listed in the sim lib directory's modelsim.ini
        set ini_file [file join $sim_lib_dir "modelsim.ini"]
        if { [file exists $ini_file] } {
            # Tell vsim to also consult the Vivado-generated ini for library lookups
            vmap -c
            set fd [open $ini_file r]
            while { [gets $fd line] >= 0 } {
                # Lines in modelsim.ini look like: libname = /path/to/lib
                if { [regexp {^(\w+)\s*=\s*(.+)$} $line -> libname libpath] } {
                    catch { vmap $libname [string trim $libpath] }
                }
            }
            close $fd
            puts "INFO: Mapped simulation libraries from $ini_file"
        } else {
            puts "WARNING: modelsim.ini not found in $sim_lib_dir"
            puts "         Add the path returned by 'Compile Simulation Libraries'."
        }
    }
}

# ---------------------------------------------------------------------------
# Step 3: Source the Vivado-exported compile script
#
# This script contains all vlog / vcom commands needed to compile IP models,
# the Block Design HDL wrapper, and the glue logic.  It was generated by
# export_simulation -simulator questa.
# ---------------------------------------------------------------------------
puts "INFO: Sourcing compile script: $compile_do"
do $compile_do
puts "INFO: Compilation complete."

# ---------------------------------------------------------------------------
# Step 4: Elaborate the testbench (vsim)
#
# Key flags:
#   -L xil_defaultlib   : Link to the Vivado default library (contains BD top)
#   -t 1ps              : Simulation time resolution
#   +acc                : Full signal access (required for "mem load" to work)
#   -onfinish stop      : Pause (not exit) at $finish so we can inspect state
#
# The "+acc" / "+access +r" flag is critical: without it Questasim may deny
# access to internal memory arrays when the mem load command runs.
# ---------------------------------------------------------------------------
set vsim_cmd "vsim"
append vsim_cmd " -t 1ps"
append vsim_cmd " +acc"
append vsim_cmd " -onfinish stop"

# Add pre-compiled library references if provided
if { $sim_lib_dir ne "" } {
    append vsim_cmd " -L xil_defaultlib"
    append vsim_cmd " -L xpm"
    append vsim_cmd " -L blk_mem_gen_v8_4_5"
    # Add further -L flags here for other IP libraries used in your design
}

if { $vsim_extra ne "" } {
    append vsim_cmd " $vsim_extra"
}

append vsim_cmd " $sim_top"

puts "INFO: Elaborating: $vsim_cmd"
eval $vsim_cmd

# ---------------------------------------------------------------------------
# Step 5: Load the ELF firmware into BRAM via mem load
#
# load_elf.tcl was produced by Vivado's write_mem_tcl command.  It contains
# one or more commands of the form:
#
#   mem load -infile /path/to/bram_init.mem -format hex \
#            /tb/DUT/bd_i/blk_mem_gen_0/U0/...
#
# The memory hierarchy paths inside load_elf.tcl are relative to the
# simulation root at the time write_mem_tcl was run.  If your testbench
# wraps the DUT under a different path, set TB_INST_PREFIX in the environment
# and the lines below will patch the paths before sourcing.
# ---------------------------------------------------------------------------
set tb_prefix [getenv TB_INST_PREFIX ""]

if { $tb_prefix ne "" } {
    # Rewrite load_elf.tcl on the fly to prepend the testbench prefix to every
    # hierarchy path argument of each "mem load" command.
    puts "INFO: Applying TB_INST_PREFIX \"$tb_prefix\" to mem load paths..."
    set fd_in  [open $load_elf_tcl r]
    set fd_out [open "${load_elf_tcl}.patched" w]
    while { [gets $fd_in line] >= 0 } {
        # Match the last token on mem load lines (the hierarchy path)
        regsub {(mem load\s+.*\s+)(\/\S+)$} $line "\\1${tb_prefix}\\2" line
        puts $fd_out $line
    }
    close $fd_in
    close $fd_out
    set active_load_tcl "${load_elf_tcl}.patched"
} else {
    set active_load_tcl $load_elf_tcl
}

puts "INFO: Loading ELF into BRAM: $active_load_tcl"
source $active_load_tcl
puts "INFO: ELF loaded into simulation memory."

# ---------------------------------------------------------------------------
# Step 6: Waveforms (skipped in batch mode or when wave_do is empty)
# ---------------------------------------------------------------------------
if { $batch_mode ne "1" && $wave_do ne "" && [file exists $wave_do] } {
    puts "INFO: Loading waveforms: $wave_do"
    do $wave_do
}

# ---------------------------------------------------------------------------
# Step 7: Run
# ---------------------------------------------------------------------------
puts "INFO: Starting simulation: run $run_time"
run $run_time
puts "INFO: Simulation finished."

# ---------------------------------------------------------------------------
# Step 8: Exit in batch / CI mode
# ---------------------------------------------------------------------------
if { $batch_mode eq "1" } {
    quit -f
}
